# https://docs.travis-ci.com/user/build-config-validation/
version: ~> 1.0

# https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: node_js
node_js:
  - "10"
install:
  - export CXX="g++-5"
  - npm install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - graphicsmagick
    - g++-5
before_script:
  - gm version
script:
  - npm run lint
  - npm test
after_script: "npm run coverage"
cache:
  directories:
    - node_modules
jobs:
  fast_finish: true
