name: Node.js v18 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
    - run: sudo apt-get install graphicsmagick

    - uses: actions/checkout@v3

    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test
