name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install GraphicsMagick
      run: |
        sudo apt-get install graphicsmagick
        gm version

    - name: Use Node.js v24
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Lint and test
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Upload code coverage to codecov
      # https://github.com/marketplace/actions/codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.lcov